// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Bindings {
  ANTHROPIC_API_KEY: string;
  DEFAULT_MODEL: string;
  AI_PROVIDER: string;
  CURSOR_API_KEY?: string;
  OPENAI_API_KEY: string;
  OPENAI_MODEL: string;
}
